- name: Install the packages
  yum:
    name: 
      - openstack-neutron
      - openstack-neutron-ml2
      - openstack-neutron-linuxbridge
      - ebtables
      - ipset
      - dnsmasq
      - libreswan
    state: present

- name: config neutron.conf
  template:
    src: neutron.conf
    dest: /etc/nova/neutron.conf
    owner: root
    group: neutron
    mode: "0640"

- name: config ml2_conf.ini
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: neutron
    mode: "0640"
